### ISSUE TITLE
Add a friend member function to a class has some question?

### ISSUE THREAD

**Issue by gongxh13** [focus000/cppprimer#3]
In c++ primer book, section 7.3.4 Friendship Revisited metioned if one class want to access another class's private members, we have two method to to.
The first method is we can add "friend" the whole class name which want to access another class''s private members to that class. For example:

    class Screen {
        // Window_mgr members can access the private parts of class Screen
        friend class Window_mgr;
        // ... rest of the Screen class
    };
Above method has no problem.
The second method is making a member function a friend,  for example in book:

    class Screen{
        //Window_mgr::clear must have been declared before class Screen
        friend void Window_mgr::clear(ScreenIndex);
        // ... rest of the Screen class
    };
This method has some problem. If we want to add Window_mgr::clear  friend to Screen, then we must first declare Window_mgr::clear,  Window_mgr::clear is this :`void clear(ScreenIndex);` , so we first declare ScreenIndex, ScreenIndex is `using ScreenIndex = std::vector<Screen>::size_type;` So we must first declare class Screen, and then declare ScreenIndex, but we how to declare Window_mgr::clear? 

Window_mgr has a private member screens:`std::vector<Screen> screens{Screen(24, 80, ' ')};`, this member need define class Screen firstly, then which should first define?

We have diffcult on declare Window_mgr::clear is because if we want to declare a class's member, we must define this member, if we define this member, we how to initial screens?

The first rigth method's whole code is below:
`========================

    #include<iostream>
    #include<vector>
    using namespace std;

    class Sales_data
    {
        /* data */
        // constructors added
    friend Sales_data add(const Sales_data&, const Sales_data&);
    friend ostream &print(ostream&, const Sales_data&);
    friend istream &saread(istream&, Sales_data&);
    public:
        Sales_data() = default;
        Sales_data(const string &s):bookNo(s){}
        Sales_data(const string &s, unsigned n, double p)
        :bookNo(s),units_sold(n),revenue(p*n){}
        Sales_data(istream &);
        Sales_data(const double &n){
            units_sold = n;
        };
        string isbn() const {return bookNo;}
    private:
        string bookNo;
        unsigned units_sold = 0;
        double revenue = 0.0;
        Sales_data& combine(const Sales_data&);
        double avg_price() const;
    };
    Sales_data add(const Sales_data&, const Sales_data&);
    ostream &print(ostream&, const Sales_data&);
    istream &saread(istream&, Sales_data&);

    double Sales_data::avg_price() const
    {
        if (units_sold)
        {
            /* code */
            return revenue/units_sold;
        }else
        {
            return 0;
        }
    }

    Sales_data& Sales_data::combine(const Sales_data& rhs)
    {
        units_sold += rhs.units_sold;
        revenue += rhs.revenue;
        return *this;
    }

    // input transactions contain ISBN, number of copies sold, and sales price
    istream &saread(istream &is, Sales_data &item){
        double price = 0;
        is >> item.bookNo >> item.units_sold >> price;
        item.revenue = price * item.units_sold;
        return is;
    }

    ostream &print(ostream &os, const Sales_data &item){
        os << item.isbn() << " " << item.units_sold << " "
           << item.revenue << " " << item.avg_price() << endl;
        return os;
    }

    Sales_data add(const Sales_data &lhs, const Sales_data &rhs)
    {
        Sales_data sum = lhs;  // copy data members from lhs into sum
        sum.combine(rhs);      // add data members from rhs into sum
        return sum;
    }

    Sales_data::Sales_data(istream &is){
        saread(is, *this);
    }

    class Screen{
        friend class Window_mgr;
    public:
        typedef std::string::size_type pos;
        Screen() = default;
        Screen(pos ht, pos wd, char c): height(ht), width(wd), contents(ht * wd, c) {}
        char get() const {return contents[cursor];}
        inline char get(pos ht, pos wd) const;
        Screen &set(char);
        Screen &set(pos, pos, char);
        Screen &display(ostream &os){
            do_display(os);return *this;
        }
        const Screen &display(ostream &os)const {
            do_display(os);return *this;
        }
        Screen &move(pos r, pos c);
        void some_member() const;
    private:
        mutable size_t access_ctr;
        pos cursor = 0;
        pos height = 0, width = 0;
        std::string contents;
        void do_display(ostream &os) const {
            os << contents;
        }
    };
    class Window_mgr
    {
    public:
        // location ID for each screem on the window
        using ScreenIndex = std::vector<Screen>::size_type;
        // reset the Screen at the given position to all blanks
        void clear(ScreenIndex);
        // add a Screen to the window and returns its index
        ScreenIndex addScreen(const Screen&);
    private:
        std::vector<Screen> screens{Screen(24, 80, ' ')};
    };

    void Window_mgr::clear(ScreenIndex i){
        // s is a reference to the Screen we want to clear
        Screen &s = screens[i];
        s.contents = string(s.height * s.width, ' ');
    }

    Window_mgr::ScreenIndex Window_mgr::addScreen(const Screen &s)
    {
        screens.push_back(s);
        return screens.size() - 1;
    }

    void Screen::some_member() const
    {
        ++access_ctr;
    }

    char Screen::get(pos ht, pos wd) const
    {
        pos row = ht * width;
        return contents[row + wd];
    }
    inline
    Screen &Screen::move(pos r, pos c)
    {
        pos row = r * width;
        cursor = row + c;
        return *this;
    }

    inline Screen &Screen::set(char c)
    {
        contents[cursor] = c;
        return *this;
    }

    inline Screen &Screen::set(pos r, pos c, char ch)
    {
        contents[r*width + c] = ch;
        return *this;
    }

    int main()
    {
    }

=========================`

**Comment by focus000** [comment]
if we just declare `Window_mgr::clear()` as a friend, we can't initial `screens` with `Screen(24, 80, ' ')`.  However, we could write a nonmember function to lead user add values to `screens`. 😂 
plz see my code in [ex7_32.h](https://github.com/focus000/cppprimer/blob/master/ch07/ex7_32.h).

**Comment by gongxh13** [comment]
> if we just declare `Window_mgr::clear()` as a friend, we can't initial `screens` with `Screen(24, 80, ' ')`. However, we could write a nonmember function to lead user add values to `screens`. 
> plz see my code in [ex7_32.h](https://github.com/focus000/cppprimer/blob/master/ch07/ex7_32.h).
